WebApplication3/Controllers/AdminController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using miniPrpject_Asp.Models;
using miniPrpject_Asp.Services;
using Rotativa.AspNetCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication3.Data;
using WebApplication3.Services;

namespace WebApplication3.Controllers
{
    public class AdminController : Controller
    {

        private readonly ApplicationDbContext _context;
        private static ApplicationDbContext contex;
        private SeanceService seanceService = new SeanceService();
        private LocalService localService = new LocalService(contex);

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult Programer_Emploi()
        {

            ViewBag.semaines = new SelectList(_context.Semaines, "Id", "NomSemaine");
            ViewBag.classes = new SelectList(_context.Classes, "Id", "code");
            ViewBag.annees = new SelectList(_context.Annees, "Id", "Nom");
            return View();
        }
        [HttpPost]
        public ActionResult Programer_emploi_etap1(int classe, int semaine, int annee)
        {
            var emploi_id = _context.Emplois.Where(
                            x =>
                            x.AnneeID == annee &&
                            x.id_niveau == classe &&
                            x.SemaineID == semaine).FirstOrDefault();
            
            ViewBag.annee = annee;
            ViewBag.semaine = semaine;
            ViewBag.classe = classe;
            ViewBag.local = _context.Locals;
            ViewBag.cours = _context.Cours;
            ViewBag.prof = _context.Professeurs;



            if (emploi_id == null)
            {
                List<DetailEmploi> detail_ei = new List<DetailEmploi>();

                return View(detail_ei);
            }
            else
            {
                var detail_emploi = _context.DetailEmplois.Where(x => x.EmploiID == emploi_id.Id).ToList();
                ViewBag.id_emploii = emploi_id.Id;
                return View(detail_emploi);
            }
        }
        [HttpPost]
        public ActionResult Programer_emploe_etap2(int idSeance, int idSemaine, int idAnnee, int idClasse,String bout,int idDetailSeance)
        {

            var locals = _context.Locals.ToList();
            var emploi_id = _context.Emplois.Where(
               x =>
               x.AnneeID == idAnnee &&
               x.SemaineID == idSemaine).Select(x =>
                 x.Id).ToList();
            List<int> localsNon = new List<int>();
            List<DetailEmploi> SeancelocalsNon = new List<DetailEmploi>();
            for (int j = 0; j < emploi_id.Count; j++)
            {
                var id = emploi_id[j];
                List<int> localsNon2 = _context.DetailEmplois.Where(x => x.EmploiID == id && x.SeanceID == idSeance).Select(x =>
                   x.Local.Id).ToList();
                List<DetailEmploi> SeancelocalsNon2 =_context.DetailEmplois.Where(x => x.EmploiID == id && x.SeanceID == idSeance).ToList();
                SeancelocalsNon.AddRange(SeancelocalsNon2);

                localsNon.AddRange(localsNon2);
            }
            for (int i = 0; i < locals.Count; i++)
            {
                if (localsNon.Contains(locals[i].Id))
                {
                    locals.Remove(locals[i]);
                }
            }
            ViewBag.localNonDisp= SeancelocalsNon;
            ViewBag.local = new SelectList(locals, "Id", "Nom");

            //Coursssssssssssùùùùùùùù

            var Proffesseurs = _context.Cours.Where(x => x.ClasseID == idClasse).Select(x =>
                     x.ProfesseurID).Distinct().ToList()
                     ;

            List<int> ProfNon = new List<int>();
            for (int j = 0; j < emploi_id.Count; j++)
            {
                var id = emploi_id[j];
                //List<int> ProfNon2 = _context.DetailEmplois.Where(x => x.EmploiID == id && x.SeanceID == idSeance).Select(x =>
                // x.Cours.Professeur.Id).ToList();
                List<int> coursid = _context.DetailEmplois.Where(x => x.EmploiID == id && x.SeanceID == idSeance).Select(x =>
                x.CoursID).ToList();
                List<int> ProfNon2 = new List<int>();
                foreach (var Cour in coursid)
                {
                    foreach (var cours in _context.Cours)
                    {
                        if (cours.Id == Cour)
                        {
                            ProfNon2.Add(cours.ProfesseurID);
                        }
                    }
                }

                ProfNon.AddRange(ProfNon2);
            }
            for (int i = 0; i < Proffesseurs.Count; i++)
            {
                if (ProfNon.Contains(Proffesseurs[i]))
                {
                    Proffesseurs.Remove(Proffesseurs[i]);
                }
            }

            List<Cours> CoursDisponib = new List<Cours>();
            for (int i = 0; i < Proffesseurs.Count; i++)
            {
                int idprof = Proffesseurs[i];

                CoursDisponib.AddRange(_context.Cours.Where(x => x.ClasseID == idClasse && x.ProfesseurID == idprof).ToList());
            }
            ViewBag.cours = new SelectList(CoursDisponib, "Id", "Nom");

            ViewBag.annee = _context.Annees.Where(x => x.Id == idAnnee).First();
            ViewBag.semaine = _context.Semaines.Where(x => x.Id == idSemaine).First();
            ViewBag.seance = _context.Seances.Where(x => x.Id == idSeance).FirstOrDefault();
            ViewBag.classe = _context.Classes.Where(x => x.Id == idClasse).First();

            ViewBag.allCour = _context.Cours;
            ViewBag.allLocal = _context.Locals;
            ViewBag.allProf = _context.Professeurs;


            if (bout == "Ajouter")
            {
               
                ViewBag.AM = 0;
            }

            else if (bout == "Modifier")
            {
                
                ViewBag.idDetailSeance=idDetailSeance;
                ViewBag.AM = 1;
            }
            return View();
        }


        [HttpPost]
        public ActionResult AjoutSeance(string idSemaine, string idSeance, string idAnnee, string idClasse, int Local, int cours,string Seance,int idDetailSeance)
        {

            int idSm = Convert.ToInt32(idSemaine);
            int idSa = Convert.ToInt32(idSeance);
            int idA = Convert.ToInt32(idAnnee);
            int idC = Convert.ToInt32(idClasse);
            if (Seance=="Modifier")
            {
                var seance = _context.DetailEmplois.Where(
                  x =>
                  x.Id == idDetailSeance).FirstOrDefault();
                seance.LocalID = Local;
                seance.CoursID = cours;
                _context.SaveChanges();
            }
            else if (Seance=="Ajouter")
            {

               

                ViewBag.sem = idSemaine;

                var emploi_id = _context.Emplois.Where(
                   x =>
                   x.AnneeID == idA &&
                   x.id_niveau == idC &&
                   x.SemaineID == idSm).FirstOrDefault();

                if (emploi_id == null)
                {

                    Emploi nouveauEmploie = new Emploi();
                    nouveauEmploie.AnneeID = idA;
                    nouveauEmploie.SemaineID = idSm;
                    nouveauEmploie.id_niveau = idC;
                    _context.Emplois.Add(nouveauEmploie);
                    _context.SaveChanges();

                    var emplois = _context.Emplois;
                    int max_id = 0;
                    foreach (var emp in emplois)
                    {
                        if (max_id < emp.Id)
                        {
                            max_id = emp.Id;
                        }
                    }


                    DetailEmploi nouvelleSeance = new DetailEmploi();
                    nouvelleSeance.EmploiID = max_id;
                    nouvelleSeance.SeanceID = idSa;
                    nouvelleSeance.LocalID = Local;
                    nouvelleSeance.CoursID = cours;
                    _context.DetailEmplois.Add(nouvelleSeance);
                    _context.SaveChanges();


                }
                else
                {
                    DetailEmploi nouvelleSeance = new DetailEmploi();
                    nouvelleSeance.EmploiID = emploi_id.Id;
                    nouvelleSeance.SeanceID = idSa;
                    nouvelleSeance.LocalID = Local;
                    nouvelleSeance.CoursID = cours;
                    _context.DetailEmplois.Add(nouvelleSeance);
                    _context.SaveChanges();
                }

            }
           
            
            return RedirectToAction("Programer_emploi_etap1Get", new { classe = idC, semaine = idSm, annee = idA });

        }

        //[HttpGet("{classe}/{semaine}/{annee}")]
        public ActionResult Programer_emploi_etap1Get(string classe, string semaine, string annee)
        {
            int idSm = Convert.ToInt32(semaine);
            int idA = Convert.ToInt32(annee);
            int idC = Convert.ToInt32(classe);

            var emploi_id = _context.Emplois.Where(
                            x =>
                            x.AnneeID == idA &&
                            x.id_niveau == idC &&
                            x.SemaineID == idSm).FirstOrDefault();

            ViewBag.annee = annee;
            ViewBag.semaine = semaine;
            ViewBag.classe = classe;
            ViewBag.local = _context.Locals;
            ViewBag.cours = _context.Cours;
            ViewBag.prof = _context.Professeurs;

WebApplication3/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using miniPrpject_Asp.Models;
using Rotativa.AspNetCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication3.Data;

namespace miniPrpject_Asp.Controllers
{
    public class ClientController : Controller
    {

        private readonly ApplicationDbContext _context;

        public ClientController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }




        public async Task<IActionResult> afficherEmploies()
        {

            ViewBag.Niveau = _context.Classes;
            ViewBag.annee = _context.Annees;
            ViewBag.Semaine = _context.Semaines;
            return View(await _context.Emplois.ToListAsync());
        }




        public ActionResult ParClasse()
        {


            ViewBag.semaines = new SelectList(_context.Semaines, "Id", "NomSemaine");
            ViewBag.classes = new SelectList(_context.Classes, "Id", "code");
            ViewBag.annees = new SelectList(_context.Annees, "Id", "Nom");
            return View();
        }
        [HttpPost]
        public ActionResult AffichageParClasse(string sub)
        {
            ViewBag.local = _context.Locals;
            ViewBag.cours = _context.Cours;
            ViewBag.prof = _context.Professeurs;
            ViewBag.niveau = _context.Classes;
            int idclasse = int.Parse(Request.Form["classe"]);
            int idsemaine = int.Parse(Request.Form["semaine"]);
            int idannee = int.Parse(Request.Form["annee"]);



            var emploi_id = _context.Emplois.Where(
                         x =>
                         x.AnneeID == idannee &&
                         x.SemaineID == idsemaine &&
                            x.id_niveau == idclasse).Select(x =>
                   x.Id).Distinct().ToList();
            List<DetailEmploi> detail = new List<DetailEmploi>();

            foreach (var idEm in emploi_id)
            {
                var detail2 = _context.DetailEmplois.Where(
                x => x.EmploiID == idEm).ToList();

                detail.AddRange(detail2);
            }




            List<infosSeance> detailPDF = new List<infosSeance>();

            foreach (var seance in detail)
            {
                infosSeance el = new infosSeance();
                el.Id = seance.Id;
                el.SeanceID = seance.SeanceID;
                el.EmploiID = seance.EmploiID;
                el.LocalID = seance.LocalID;
                el.CoursID = seance.CoursID;
                foreach (var cour in _context.Cours)
                {
                    if (cour.Id == seance.CoursID)
                    {
                        el.Cours = cour.Nom;

                        foreach (var prof in _context.Professeurs)
                        {
                            if (prof.Id == cour.ProfesseurID)
                            {
                                el.Prof = prof.Nom;
                            }

                        }
                    }
                }
                foreach (var lcl in _context.Locals)
                {
                    if (lcl.Id == seance.LocalID)
                    {
                        el.Local = lcl.Nom;
                    }
                }

                detailPDF.Add(el);

            }





            if (sub == "Afficher")
            {
                return View(detail);
            }
            else
            {
                return new ViewAsPdf("AffichageParClassePdf", detailPDF);
            }
        }


        public ActionResult ParLocal()
        {

            ViewBag.semaines = new SelectList(_context.Semaines, "Id", "NomSemaine");
            ViewBag.locals = new SelectList(_context.Locals, "Id", "Nom");
            ViewBag.annees = new SelectList(_context.Annees, "Id", "Nom");
            return View();
        }
        [HttpPost]
        public ActionResult AffichageParLocal(int semaine, int local, int annee, string sub)
        {
            ViewBag.local = _context.Locals;
            ViewBag.cours = _context.Cours;
            ViewBag.prof = _context.Professeurs;
            ViewBag.niveau = _context.Classes;
            var emploi_id = _context.Emplois.Where(
                           x =>
                           x.AnneeID == annee &&
                           x.SemaineID == semaine).Select(x =>
                     x.Id).Distinct().ToList();
            List<DetailEmploi> detail = new List<DetailEmploi>();

            foreach (var idEm in emploi_id)
            {
                var detail2 = _context.DetailEmplois.Where(
                x => x.EmploiID == idEm &&
                x.LocalID == local).ToList();

                detail.AddRange(detail2);
            }

            List<infosSeance> detailPDF = new List<infosSeance>();

            foreach (var seance in detail)
            {
                infosSeance el = new infosSeance();
                el.Id = seance.Id;
                el.SeanceID = seance.SeanceID;
                el.EmploiID = seance.EmploiID;
                el.LocalID = seance.LocalID;
                el.CoursID = seance.CoursID;
                foreach (var cour in _context.Cours)
                {
                    if (cour.Id == seance.CoursID)
                    {
                        el.Cours = cour.Nom;

                        foreach (var prof in _context.Professeurs)
                        {
                            if (prof.Id == cour.ProfesseurID)
                            {
                                el.Prof = prof.Nom;
                            }

                        }
                    }
                }
                foreach (var lcl in _context.Locals)
                {
                    if (lcl.Id == seance.LocalID)
                    {
                        el.Local = lcl.Nom;
                    }
                }

                detailPDF.Add(el);

            }


            if (sub == "Afficher")
            {
                return View(detailPDF);
            }


            else
            {


                return new ViewAsPdf("AffichageParLocalPdf", detailPDF);
            }
        }



    }

}

WebApplication3/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>  Espace Administrateur</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="~/ssets/css/line-awesome.min.css">
    <link rel="stylesheet" href="~/assets/css/chartist.min.css">
    <link rel="stylesheet" href="~/assets/css/bootstrap-toggle.min.css">
    <link rel="stylesheet" href="~/assets/css/jquery-ui.min.css">
    <link rel="stylesheet" href="~/assets/css/jquery.scrollbar.min.css">
    <link rel="stylesheet" href="~/assets/css/ready.css">
    <link rel="stylesheet" href="~/assets/css/demo.css">
    <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
</head>
<body>
    <div class="wrapper">
        <div class="main-header">
            <div class="logo-header">
                <a href="index.html" class="logo">
                    Espace Administrateur
                </a>
                <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <button class="topbar-toggler more"><i class="la la-ellipsis-v"></i></button>
            </div>
            <nav class="navbar navbar-header navbar-expand-lg" style="background-color:cadetblue">
                <div class="container-fluid">


                    <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">


                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false"> <img src="../assets/img/profile.jpg" alt="user-img" width="36" class="img-circle"><span style="color:white"> @Context.Session.GetString("username")</span></span> </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li>
                                    <div class="user-box">
                                        <div class="u-img"><img src="../assets/img/profile.jpg" alt="user"></div>
                                        <div class="u-text">
                                            <h4>Welcome @Context.Session.GetString("username")</h4>
                                            <p class="text-muted">rianhizrian@gmail.com</p><a href="profile.html" class="btn btn-rounded btn-danger btn-sm">View Profile</a>
                                        </div>
                                    </div>
                                </li>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#"><i class="ti-user"></i> My Profile</a>
                            </ul>
                            <!-- /.dropdown-user -->
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="sidebar" style="color:Black;">
            <div class="scrollbar-inner sidebar-wrapper">
                <div class="user">

                    <div class="info" style="margin-top:100px;">
                        <a class="" data-toggle="collapse" href="#collapseExample" aria-expanded="true">
                            <span style="color:black">
                                Gestion des Locaux
                                <span class="caret"></span>
                            </span>
                        </a>
                        <div class="clearfix"></div>

                        <div class="collapse in" id="collapseExample" aria-expanded="true" style="">
                            <ul class="nav">
                                <li>
                                    <a asp-area="" asp-controller="Locals" asp-action="Create">
                                        <span class="link-collapse" style="color:black">Ajouter Local</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Locals" asp-action="Index">
                                        <span class="link-collapse" style="color:black">Liste des Locaux</span>
                                    </a>
                                </li>
                            </ul>
                        </div>


                    </div>
                </div>

                <div class="user">

                    <div class="info">
                        <a class="" data-toggle="collapse" href="#profExample" aria-expanded="true">
                            <span style="color:black">
                                Gestion des Prof
                                <span class="caret"></span>
                            </span>
                        </a>
                        <div class="clearfix"></div>

                        <div class="collapse in" id="profExample" aria-expanded="true" style="">
                            <ul class="nav">
                                <li>
                                    <a asp-area="" asp-controller="Professeurs" asp-action="Create">
                                        <span class="link-collapse" style="color:black">Ajouter Prof</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Professeurs" asp-action="Index">
                                        <span class="link-collapse" style="color:black">Liste des Prof</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    </div>




                <ul class="nav">

                    <li class="nav-item">

                        <div class="info">
                            <a class="" data-toggle="collapse" href="#collapseExample1" aria-expanded="true">
                                <span style="color:black">
                                    Extraire Planning
                                    <span class="caret"></span>
                                </span>
                            </a>
                            <div class="clearfix"></div>

                            <div class="collapse in" id="collapseExample1" aria-expanded="true" style="">
                                <ul class="nav">
                                    <li>
                                        <a asp-area="" asp-controller="Admin" asp-action="ParLocal">
                                            <span class="link-collapse" style="color:black">Par Local</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="Admin" asp-action="ParProfesseur">
                                            <span class="link-collapse" style="color:black">Par Professeur</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-area="" asp-controller="Admin" asp-action="ParClasse">
                                            <span class="link-collapse" style="color:black">Par Classe</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Admin" asp-action="Programer_Emploi">
                            <p style="color:black">Programmer Un Emploi</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Seance" asp-action="afficherEmploies">
                            <p style="color:black">Listes des Emploi</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Admin" asp-action="Disponibilite">
                            <p style="color:black">Locaux Disponibles</p>
                        </a>
                    </li>


                </ul>
                </div>
            </div>
        <div class="main-panel">
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="container-fluid">
            <nav class="pull-left">
                <ul class="nav">
                    <li class="nav-item">
                        Projet ASP.Net Core
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">

                        </a>
                    </li>
                    <li class="nav-item">

                    </li>
                </ul>
            </nav>

        </div>
    </footer>
    </div>
    </div>
    </div>
    </div>
    <!-- Modal -->

</body>

<script src="~/assets/js/core/jquery.3.2.1.min.js"></script>
<script src="~/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="~/assets/js/core/popper.min.js"></script>
<script src="~/assets/js/core/bootstrap.min.js"></script>
<script src="~/assets/js/plugin/chartist/chartist.min.js"></script>
<script src="~/assets/js/plugin/chartist/plugin/chartist-plugin-tooltip.min.js"></script>
<script src="~/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>
<script src="~/assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>
<script src="~/assets/js/plugin/jquery-mapael/jquery.mapael.min.js"></script>
<script src="~/assets/js/plugin/jquery-mapael/maps/world_countries.min.js"></script>
<script src="~/assets/js/plugin/chart-circle/circles.min.js"></script>
<script src="~/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<script src="~/assets/js/ready.js"></script>
</html>

WebApplication3/Views/Shared/_Layout1.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>  Espace Administrateur</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="~/ssets/css/line-awesome.min.css">
    <link rel="stylesheet" href="~/assets/css/chartist.min.css">
    <link rel="stylesheet" href="~/assets/css/bootstrap-toggle.min.css">
    <link rel="stylesheet" href="~/assets/css/jquery-ui.min.css">
    <link rel="stylesheet" href="~/assets/css/jquery.scrollbar.min.css">
    <link rel="stylesheet" href="~/assets/css/ready.css">
    <link rel="stylesheet" href="~/assets/css/demo.css">
    <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
</head>
<body>
    <div class="wrapper">

        <div class="main-header">
            <div class="logo-header">
                <a href="index.html" class="logo">
                    Espace Professeur
                </a>
                <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
        <div class="sidebar">
            <div class="scrollbar-inner sidebar-wrapper">
               
                <ul class="nav">
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Client" asp-action="ParClasse">
                            <p> Extraire Planning Par Classe</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Client" asp-action="ParLocal">
                            <p>Extraire Planning  Par Local</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Client" asp-action="afficherEmploies">
                            <p>Listes des emploies du temps</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="container-fluid">
            <nav class="pull-left">
                <ul class="nav">
                    <li class="nav-item">
                        Projet ASP.Net Core
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">

                        </a>
                    </li>
                    <li class="nav-item">

                    </li>
                </ul>
            </nav>

        </div>
    </footer>
    </div>
    </div>
    </div>
    </div>
    <!-- Modal -->

</body>

<script src="~/assets/js/core/jquery.3.2.1.min.js"></script>
<script src="~/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="~/assets/js/core/popper.min.js"></script>
<script src="~/assets/js/core/bootstrap.min.js"></script>
<script src="~/assets/js/plugin/chartist/chartist.min.js"></script>
<script src="~/assets/js/plugin/chartist/plugin/chartist-plugin-tooltip.min.js"></script>
<script src="~/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>
<script src="~/assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>
<script src="~/assets/js/plugin/jquery-mapael/jquery.mapael.min.js"></script>
<script src="~/assets/js/plugin/jquery-mapael/maps/world_countries.min.js"></script>
<script src="~/assets/js/plugin/chart-circle/circles.min.js"></script>
<script src="~/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<script src="~/assets/js/ready.js"></script>
</html>